version: "3.8"
services:
  rails-api:
    build:
      context: ./guestbook_api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./guestbook_api:/rails
    environment:
      RAILS_ENV: development
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/mydb"
    depends_on:
      - postgres
    command: bash -c "bundle install && bin/rails db:prepare && bin/rails server -b 0.0.0.0"

  vue-frontend:
    build:
      context: ./guestbook-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./guestbook-frontend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - rails-api
    command: npm run dev -- --host

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
