version: "3.8"

services:
  rails-api:
    build:
      context: ./guestbook_api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/mydb"
    depends_on:
      - postgres
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
